on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Publish
        run: gradle check publish --no-configure-on-demand --no-daemon
        env:
          ORG_GRADLE_PROJECT_githubUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_githubPassword: ${{ github.token }}